spring:
  application:
    name: image-service

  r2dbc:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres.social-network-db:5432/spring_microservice_course_db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres.social-network-db:5432/spring_microservice_course_db}

  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis.social-network-db}
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:password}
      database: 0
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres.social-network-db:5432/spring_microservice_course_db}
    username: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    driver-class-name: org.postgresql.Driver

  cloud:
    aws:
      credentials:
        access-key: ${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY:test}
        secret-key: ${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY:test}
      s3:
        bucket-name: images
        endpoint: ${SPRING_CLOUD_AWS_S3_ENDPOINT:http://localstack.social-network-db:4566}

  aop:
    auto: true
    proxy-target-class: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    org.springframework.r2dbc: DEBUG
    liquibase: INFO
    by.losik.imageservice: DEBUG

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs