apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: social-network-db
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXM=  # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: social-network-users
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXM=  # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: social-network-comments
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXM=  # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: social-network-images
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXM=  # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: social-network-db
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: social-network-gateway
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: social-network-users
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: social-network-images
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: social-network-comments
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: social-network-db
type: Opaque
data:
  database: YWN0aXZpdHlfZGI= # activity_db
  password: cGFzc3dvcmQ= # password
  username: YWRtaW4= # admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: social-network-activities
type: Opaque
data:
  database: YWN0aXZpdHlfZGI= # activity_db
  password: cGFzc3dvcmQ= # password
  username: YWRtaW4= # admin
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: social-network-db
type: Opaque
data:
  access-key: dGVzdA==  # test
  secret-key: dGVzdA==  # test
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: social-network-images
type: Opaque
data:
  access-key: dGVzdA==  # test
  secret-key: dGVzdA==  # test
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: social-network-db
type: Opaque
data:
  broker-id: MQ==  # 1
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: social-network-activities
type: Opaque
data:
  broker-id: MQ==  # 1