apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: social-network-gateway
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: social-network-users
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: social-network-gateway
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-access-sa
  namespace: social-network-db
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-service-sa
  namespace: social-network-images
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comment-like-service-sa
  namespace: social-network-comments
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: activity-service-sa
  namespace: social-network-activities
automountServiceAccountToken: false